import re

texto = '''
"id": 2,
                            "name": "Agilidad"
                        }, {
                            "id": 3,
                            "name": "Android"
                        }, {
                            "id": 4,
                            "name": "Angular"
                        }, {
                            "id": 5,
                            "name": "Angularjs"
                        }, {
                            "id": 6,
                            "name": "Apache Camel"
                        }, {
                            "id": 7,
                            "name": "Appium"
                        }, {
                            "id": 8,
                            "name": "AWS"
                        }, {
                            "id": 10,
                            "name": "BA"
                        }, {
                            "id": 11,
                            "name": "Bitbucket"
                        }, {
                            "id": 12,
                            "name": "Bootstrap"
                        }, {
                            "id": 13,
                            "name": "Cassandra"
                        }, {
                            "id": 14,
                            "name": "Cascada"
                        }, {
                            "id": 16,
                            "name": "Confluence"
                        }, {
                            "id": 17,
                            "name": "CSS"
                        }, {
                            "id": 18,
                            "name": "Cucumber"
                        }, {
                            "id": 19,
                            "name": "CX"
                        }, {
                            "id": 20,
                            "name": "DDD"
                        }, {
                            "id": 21,
                            "name": "Design Thinking"
                        }, {
                            "id": 22,
                            "name": "DevOps"
                        }, {
                            "id": 23,
                            "name": "Docker"
                        }, {
                            "id": 24,
                            "name": "Excel"
                        }, {
                            "id": 25,
                            "name": "Express.js"
                        }, {
                            "id": 26,
                            "name": "Express/Node"
                        }, {
                            "id": 28,
                            "name": "GitHub"
                        }, {
                            "id": 29,
                            "name": "GitLab"
                        }, {
                            "id": 31,
                            "name": "GoLang"
                        }, {
                            "id": 32,
                            "name": "GCP"
                        }, {
                            "id": 35,
                            "name": "HTML"
                        }, {
                            "id": 36,
                            "name": "CI/CD"
                        }, {
                            "id": 38,
                            "name": "iOS"
                        }, {
                            "id": 39,
                            "name": "iOS Swift"
                        }, {
                            "id": 40,
                            "name": "ISTQB"
                        }, {
                            "id": 41,
                            "name": "Java"
                        }, {
                            "id": 42,
                            "name": "Java Spring Boot"
                        }, {
                            "id": 43,
                            "name": "Jira"
                        }, {
                            "id": 44,
                            "name": "Kanban"
                        }, {
                            "id": 48,
                            "name": "Kubernetes"
                        }, {
                            "id": 49,
                            "name": "Lenguaje PHP"
                        }, {
                            "id": 50,
                            "name": "Linux"
                        }, {
                            "id": 52,
                            "name": "Metodologias y Herramientas ágiles"
                        }, {
                            "id": 53,
                            "name": "Microservicios"
                        }, {
                            "id": 54,
                            "name": "Microsoft Project"
                        }, {
                            "id": 55,
                            "name": "Mobile"
                        }, {
                            "id": 57,
                            "name": "Mongo DB"
                        }, {
                            "id": 58,
                            "name": "MS"
                        }, {
                            "id": 59,
                            "name": "MySQL"
                        }, {
                            "id": 60,
                            "name": "NestJS"
                        }, {
                            "id": 63,
                            "name": "Openshift"
                        }, {
                            "id": 65,
                            "name": "Perl"
                        }, {
                            "id": 66,
                            "name": "PHP"
                        }, {
                            "id": 67,
                            "name": "PMP"
                        }, {
                            "id": 68,
                            "name": "PostgresSQL"
                        }, {
                            "id": 69,
                            "name": "Power BI"
                        }, {
                            "id": 70,
                            "name": "Python"
                        }, {
                            "id": 71,
                            "name": "React"
                        }, {
                            "id": 73,
                            "name": "Redux"
                        }, {
                            "id": 74,
                            "name": "RxJs"
                        }, {
                            "id": 75,
                            "name": "Safe"
                        }, {
                            "id": 77,
                            "name": "Selenium"
                        }, {
                            "id": 78,
                            "name": "Serenity"
                        }, {
                            "id": 79,
                            "name": "SOAP"
                        }, {
                            "id": 80,
                            "name": "SQL"
                        }, {
                            "id": 81,
                            "name": "T-SQL"
                        }, {
                            "id": 83,
                            "name": "TDD"
                        }, {
                            "id": 84,
                            "name": "Terraform"
                        }, {
                            "id": 85,
                            "name": "Trello"
                        }, {
                            "id": 86,
                            "name": "UML"
                        }, {
                            "id": 88,
                            "name": "JAVA/SPRING"
                        }, {
                            "id": 89,
                            "name": "Design thinking"
                        }, {
                            "id": 90,
                            "name": "AS 400"
                        }, {
                            "id": 91,
                            "name": "Scrum"
                        }, {
                            "id": 92,
                            "name": "Scrum Masters y Product Owners o similares."
                        }, {
                            "id": 95,
                            "name": "Mysql"
                        }, {
                            "id": 96,
                            "name": "Postgres"
                        }, {
                            "id": 97,
                            "name": "Tableau"
                        }, {
                            "id": 99,
                            "name": "Inglés"
                        }, {
                            "id": 100,
                            "name": ".NET"
                        }, {
                            "id": 101,
                            "name": "Azure DevOps"
                        }, {
                            "id": 104,
                            "name": "Node JS"
                        }, {
                            "id": 105,
                            "name": "NodeJS"
                        }, {
                            "id": 106,
                            "name": "Nodejs"
                        }, {
                            "id": 107,
                            "name": "ReactJS"
                        }, {
                            "id": 109,
                            "name": "Spring Java"
                        }, {
                            "id": 111,
                            "name": "UX / UI"
                        }, {
                            "id": 114,
                            "name": "Google Cloud"
                        }, {
                            "id": 120,
                            "name": "go"
                        }, {
                            "id": 134,
                            "name": "RPG"
                        }, {
                            "id": 170,
                            "name": "Metodologías y Herramientas Ágiles"
                        }, {
                            "id": 171,
                            "name": "M3.0"
                        }, {
                            "id": 174,
                            "name": "NgRx"
                        }, {
                            "id": 175,
                            "name": "redux"
                        }, {
                            "id": 192,
                            "name": "Sc..."
                        }, {
                            "id": 193,
                            "name": "C#"
                        }]
'''

valores = re.findall(r'"name":\s*"([^"]+)"', texto)
print(valores)